# Permalinks
permalink:        pretty

# Setup
title:            Chris Aversa
tagline:          Machine Learning Engineer
description:      Machine Learning Engineer
url:              http://stevebottos.github.io
baseurl:          /chrisaversa.github.io/chrisaversa
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name:           Steve Bottos
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com
